In [1]:
import numpy as np

In [2]:
array1= np.array([1,2,3])
print('array1 type : ', type(array1))
print('array1 array 형태 : ', array1.shape)

array1 type :  <class 'numpy.ndarray'>
array1 array 형태 :  (3,)


In [3]:
array2= np.array([[1,2,3],
                 [2,3,4]])
print('array2 type : ', type(array2))
print('array2 array 형태 : ', array2.shape)

array2 type :  <class 'numpy.ndarray'>
array2 array 형태 :  (2, 3)


In [6]:
array3 = np.array([[1,2,3]])
print('array3 type : ', type(array3))
print('array3 array 형태 : ', array3.shape)

array3 type :  <class 'numpy.ndarray'>
array3 array 형태 :  (1, 3)


In [9]:
print('array1 : {:0}차원, array2 : {:1}차원, array3 : {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 : 1차원, array2 : 2차원, array3 :  2차원


In [11]:
list1= [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [12]:
list2 = [1,2, 'test']
array2= np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


- int형 값과 문자열이 섞여있는 list2를 ndarray로 변환한 array2는 숫자형 값 1, 2가 모두 문자열 값인 '1', '2'로 변환됐습니다.
- int형과 flaot형이 섞여 있는 list3의 경우도 int1, 2가 모두 1. 2.인 float64형으로 변환됐습니다. 

### astype : ndarray 내 데이터 값의 타입 변경

보통 메모리를 절약해야 하는 경우에 보통 이용됩니다. 
가령, int 형으로 충분한 경우인데, 데이터 타입이 float이라면 int 형으로 바꿔서 메모리를 절약할 수 있습니다.

파이썬 기반의 머신러닝 알고리즘은 대부분 메모리로 **데이터를 전체 로딩한 다음 이를 기바능로 알고리즘을 적용하기 때문에**
대용량의 데이터를 로딩할 때에 수행속도가 느려지거나 메모리 부족으로 오류가 발생할 수 있습니다. 

In [13]:
array_int = np.array([1,2,3])
array_float =array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [14]:
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [15]:
array_float1 = np.array([1.1, 2.2, 3.3])
array_int2=  array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


### np.arange / np.zeros / np.ones

특정 크기와 차원을 가진 ndarray를 연속값이나 0또는 1로 초기화해 쉽게 생성해야할 필요가 있는 경우가 발생할 수 있다. 
이 경우 위의 함수들을 이용해 쉽게 ndarray를 생성할 수 있다.

In [16]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [17]:
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [18]:
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape()

In [19]:
array1= np.arange(10)
print('array1 : \n', array1)

array1 : 
 [0 1 2 3 4 5 6 7 8 9]


In [20]:
array2= array1.reshape(2,5)
print('array2 : \n', array2)

array2 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [23]:
array3= array1.reshape(5,2)
print('array3 : \n', array3)

array3 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


reshape()를 실전에서 더욱 효율적으로 사용하는 경우는 아마도 인자로 -1을 적용하는 경우

-1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환해준다. 

In [24]:
array1 = np.arange(10)
print(array1)
array2= array1.reshape(-1, 5)
print('array2 shape : ', array2.shape)
array3 = array1.reshape(5 , -1)
print('array3 shape : ', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape :  (2, 5)
array3 shape :  (5, 2)


-1 인자는 reshape(-1, 1)와 같은 형태로 자주 사용된다. 

ndarray는 tolist() 매서드를 이용해 리스트 자료형으로 반환할 수 있다. 
때로는 리스트 자료형을 print를 이용해 출력할 떄 시각적으로 더 이해하기 쉬울수 있어
nd array를 list로 변환해 출력하기도 한다. 

In [26]:
array1= np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d : \n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape', array6.shape)

array3d : 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape (8, 1)


### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

1. 특정한 데이터만 추출 : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 변환
2. 슬라이싱(Slicing) : 슬라이싱은 연속된 인덱스 상의 ndarray를 추출하는 방식
3. 팬시 인덱싱(Fancy Indexing) : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환한다. 
4. 불린 인덱싱(Boolean Indexing) : 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환합니다.

In [27]:
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start =1, stop=10)
print('array1: ', array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2] 
print('value : ', value)
print(type(value))

array1:  [1 2 3 4 5 6 7 8 9]
value :  3
<class 'numpy.int32'>


In [29]:
print('맨 뒤의 값 : ', array1[-1], ', 맨 뒤에서 두번째 값 : ', array1[-2])

맨 뒤의 값 :  9 , 맨 뒤에서 두번째 값 :  8


In [30]:
array1[0] = 9
array1[8] =0
print('array1 :', array1)

array1 : [9 2 3 4 5 6 7 8 0]


In [31]:
array1d= np.arange(start=1, stop = 10)
array2d = array1d.reshape(3,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
print('(row =0, col = 0) index 가리키는 값:', array2d[0,0])
print('(row =0, col = 1) index 가리키는 값:', array2d[0,1])
print('(row =1, col = 0) index 가리키는 값:', array2d[1,0])
print('(row =2, col = 2) index 가리키는 값:', array2d[2,2])

(row =0, col = 0) index 가리키는 값: 1
(row =0, col = 1) index 가리키는 값: 2
(row =1, col = 0) index 가리키는 값: 4
(row =2, col = 2) index 가리키는 값: 9


In [34]:
array1 = np.arange(start = 1, stop = 10)
print(array1)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [35]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [38]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0, 1], 2] => ', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] =>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ', array5.tolist())

array2d[[0, 1], 2] =>  [3, 6]
array2d[[0,1], 0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


In [39]:
array1d=  np.arange(1, 10)

In [40]:
array1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
array3 = array1d[array1d>5]
print('array1d > 5 불린 인덱싱 결과 값 : ', array3)

array1d > 5 불린 인덱싱 결과 값 :  [6 7 8 9]


In [43]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])